apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: roguelearn-social-base

resources:
- deployment.yaml
- service.yaml
- ingress.yaml

commonLabels:
  app: roguelearn-social-app
  version: v1.0.0

namespace: roguelearn-social

images:
- name: roguelearn/social-api
  newTag: latest