apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: roguelearn-staging

namespace: roguelearn-staging

resources:
- ../../base

patchesStrategicMerge:
- deployment-patch.yaml

commonLabels:
  environment: staging

images:
- name: roguelearn/dotnet-app
  newTag: staging-latest

replicas:
- name: roguelearn-deployment
  count: 2

configMapGenerator:
- name: roguelearn-config
  literals:
  - ASPNETCORE_ENVIRONMENT=Staging
  - LOG_LEVEL=Debug