# Executor needs this because it creates and manages K8s Jobs
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: executor-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: executor-role
  namespace: default
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: executor-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: executor-sa
    namespace: default
roleRef:
  kind: Role
  name: executor-role
  apiGroup: rbac.authorization.k8s.io
