apiVersion: apps/v1
kind: Deployment
metadata:
  name: roguelearn-social-deployment
spec:
  template:
    spec:
      containers:
      - name: roguelearn-social-container
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Staging"
        - name: LOG_LEVEL
          value: "Debug"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"