apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: roguelearn-base

resources:
- deployment.yaml
- service.yaml
- ingress.yaml

commonLabels:
  app: roguelearn-app
  version: v1.0.0

namespace: roguelearn

images:
- name: roguelearn/user-api
  newTag: latest