apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- ingress.yaml

images:
- name: soybean2610/roguelearn-user-api
  newName: soybean2610/roguelearn-user-api
  newTag: latest